project:
  type: presentation
  output-dir: docs

format:
  revealjs:
    theme: simple
    slide-number: true
    chalkboard: true

title: "Your Presentation Title"
author: "Your Name"
date: "2024-01-01"